"""Generate pgfplots figure inputs for the design-comparison section (task P2).

Reads the committed final run `outputs/design_exercise/rule_comparison.csv`
(legacy rule labels normalized via `config.canonical_rule_label`) and writes
two auto-generated TeX fragments to `paper/figures/`:

    fig_winshare.tex   win share vs alpha, panels: average-coordinate / linear-mean
    fig_regret.tex     mean cell-best regret vs alpha, same panels

The fragments contain tikzpicture/axis environments only; the figure
environments, captions, and labels live in
`paper/sections/06_design_comparison.tex`. Values are averages over the
(n, k) grid at each alpha — exactly the aggregation of Tables
tab:regime-wins and tab:regime-regret (cf. `scripts/consistency_check.py`).

Run: uv run python scripts/make_figures.py
"""

from __future__ import annotations

import csv
from collections import defaultdict
from pathlib import Path

from config import RULE_DISPLAY, canonical_rule_label

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "paper" / "figures"
ALPHAS = (0.1, 0.3, 1.0, 3.0, 10.0)
RULE_NAMES = tuple(RULE_DISPLAY[k] for k in ("discrete", "quadratic", "manhattan"))
METRICS = (("coord_avg", "Average-coordinate"), ("mean_linear", "Linear-mean"))
STYLES = {
    RULE_NAMES[0]: "solid, mark=*",
    RULE_NAMES[1]: "dashed, mark=square*",
    RULE_NAMES[2]: "densely dotted, mark=triangle*",
}
HEADER = (
    "% Auto-generated by scripts/make_figures.py from\n"
    "% outputs/design_exercise/rule_comparison.csv. Do not edit by hand.\n"
)


def load() -> dict:
    """{(metric, rule, alpha): mean value over (n,k)} for win share and regret."""
    acc = defaultdict(list)
    with (ROOT / "outputs" / "design_exercise" / "rule_comparison.csv").open() as f:
        for row in csv.DictReader(f):
            rule = canonical_rule_label(row["rule"])
            key = (row["metric"], rule, float(row["alpha"]))
            acc[("win", *key)].append(float(row["win_share"]))
            acc[("regret", *key)].append(float(row["mean_regret"]))
    return {k: sum(v) / len(v) for k, v in acc.items()}


def axis(stat: str, metric_key: str, title: str, ylabel: str, ymax: str,
         data: dict, legend_name: str | None) -> str:
    lines = [
        r"\begin{tikzpicture}",
        r"\begin{axis}[",
        r"  width=0.48\textwidth, height=5.4cm,",
        r"  xmode=log, log ticks with fixed point,",
        r"  xtick={0.1,0.3,1,3,10}, xticklabels={0.1,0.3,1,3,10},",
        r"  xlabel={$\alpha$}, ylabel={" + ylabel + r"},",
        r"  ymin=0, ymax=" + ymax + r",",
        r"  title={\small " + title + r"}, label style={font=\small},",
        r"  tick label style={font=\small},",
    ]
    if legend_name:
        lines += [
            r"  legend to name=" + legend_name + r",",
            r"  legend columns=3, legend style={font=\small, /tikz/every even column/.append style={column sep=0.4cm}},",
        ]
    lines.append(r"]")
    for rule in RULE_NAMES:
        pts = " ".join(
            f"({a:g},{data[(stat, metric_key, rule, a)]:.4f})" for a in ALPHAS
        )
        lines.append(rf"\addplot[{STYLES[rule]}] coordinates {{{pts}}};")
        if legend_name:
            lines.append(rf"\addlegendentry{{{rule}}}")
    lines += [r"\end{axis}", r"\end{tikzpicture}"]
    return "\n".join(lines)


def write_figure(name: str, stat: str, ylabel: str, ymax: str, data: dict) -> None:
    legend = f"leg:{name}"
    parts = [HEADER]
    parts.append(axis(stat, METRICS[0][0], METRICS[0][1], ylabel, ymax, data, legend))
    parts.append(r"\hfill")
    parts.append(axis(stat, METRICS[1][0], METRICS[1][1], ylabel, ymax, data, None))
    parts.append(r"\par\smallskip\centerline{\pgfplotslegendfromname{" + legend + r"}}")
    path = OUT / f"fig_{name}.tex"
    path.write_text("\n".join(parts) + "\n")
    print(f"wrote {path.relative_to(ROOT)}")


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    data = load()
    write_figure("winshare", "win", "Win share", "1.05", data)
    write_figure("regret", "regret", "Mean cell-best regret", "0.055", data)


if __name__ == "__main__":
    main()
